#!/usr/bin/env bash
set -ex

BASEDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

build () {
	VERSION=$1
	LATEST=${2:-0}
	cd ${BASEDIR}/${VERSION}
	docker pull postgres:${VERSION}-alpine
	if [ ${LATEST} -eq 0 ]; then
		docker buildx build \
			--platform linux/amd64,linux/arm64 \
			-t jlsalvador/postgres:${VERSION}-alpine \
			--push .
	else
		docker buildx build \
			--platform linux/amd64,linux/arm64 \
			-t jlsalvador/postgres \
			-t jlsalvador/postgres:latest \
			-t jlsalvador/postgres:${VERSION}-alpine \
			--push .
	fi
}

VERSIONS=(13 14)
for VERSION in 13 14; do
	if [ ${VERSION} -eq ${VERSIONS[-1]} ]; then
		LATEST=1
	else
		LATEST=0
	fi
	build ${VERSION} ${LATEST}
done

