#!/usr/bin/env bash
set -ex

BUILDER="docker_builder"
IMAGE="jlsalvador/postgres"

build () {
	VERSION=$1
	LATEST=${2:-0}
	TAGS=("${IMAGE}:${VERSION}-alpine")
	if [ "${LATEST}" -eq 0 ]; then
		TAGS+=("${IMAGE}" "${IMAGE}:latest")
	fi

	ARGS=()
	for TAG in "${TAGS[@]}"; do
		ARGS+=("--tag" "${TAG}")
	done
	docker pull "postgres:${VERSION}-alpine"
	docker buildx build \
		--build-arg VERSION="${VERSION}" \
		--platform linux/amd64,linux/arm64 \
		"${ARGS[@]}" \
		--push \
		.
}

cleanup() {
	docker buildx rm "${BUILDER}"
}

trap cleanup ERR EXIT

docker buildx create --use --name "${BUILDER}"
VERSIONS=(12 13 14 15 16 17)
for VERSION in "${VERSIONS[@]}"; do
	if [ "${VERSION}" -eq "${VERSIONS[-1]}" ]; then
		LATEST=1
	else
		LATEST=0
	fi
	build "${VERSION}" "${LATEST}"
done
