apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone # https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.5/git-clone.yaml
      workspaces:
      - name: output
        workspace: git-source

    - name: build-image-v13-amd64
      runAfter:
      - fetch-from-git
      taskRef:
        name: buildah
      params:
      - name: IMAGE
        value: jlsalvador/postgres
      - name: CONTEXT
        value: 13

    - name: build-image-v13-arch64
      runAfter:
      - fetch-from-git
      taskRef:
        name: buildah
      params:
      - name: IMAGE
        value: jlsalvador/postgres
      - name: CONTEXT
        value: 13

    - name: build-image-v14-amd64
      runAfter:
      - fetch-from-git
      taskRef:
        name: buildah
      params:
      - name: IMAGE
        value: jlsalvador/postgres
      - name: CONTEXT
        value: 14

    - name: build-image-v14-arch64
      runAfter:
      - fetch-from-git
      taskRef:
        name: buildah
      params:
      - name: IMAGE
        value: jlsalvador/postgres
      - name: CONTEXT
        value: 14
